import PageLayout from "@/components/PageLayout";
import { AlertTriangle } from "lucide-react";

const Disclaimers = () => {
  return (
    <PageLayout>
      <section className="pt-32 pb-16">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="max-w-7xl mx-auto">
            <h1 className="font-display text-4xl md:text-5xl font-bold text-foreground mb-6">
              Disclaimers – Important Information
            </h1>
            <p className="text-xl text-muted-foreground mb-8">
              Reluno Legal AI is an informational tool only.
            </p>
            <p className="text-sm text-muted-foreground mb-12">
              <strong>Effective Date:</strong> December 20, 2025
            </p>

            <div className="bg-destructive/10 border border-destructive/50 rounded-xl p-6 mb-12">
              <div className="flex items-start gap-4">
                <AlertTriangle className="w-8 h-8 text-destructive flex-shrink-0 mt-1" />
                <div>
                  <h2 className="font-display text-xl font-bold text-foreground mb-2">Critical Notice</h2>
                  <p className="text-foreground">
                    Reluno Legal AI provides AI-powered tools for legal questions, document generation, claim tracking, workflow automation, and analytics. <strong>These tools are for informational and organizational purposes only.</strong> They are not legal advice and should not be relied upon as such.
                  </p>
                </div>
              </div>
            </div>

            <div className="prose prose-lg max-w-none">
              <h2 className="font-display text-2xl font-bold text-foreground mt-12 mb-4">1. No Legal Advice</h2>
              <p className="text-muted-foreground mb-8">
                Reluno Legal AI is not a law firm, attorney, or substitute for professional legal counsel. All outputs from our Services—including AI-generated answers, document templates, insights, and suggestions—are general in nature and may not apply to your specific situation. We do not form attorney-client relationships with our users. For legal advice tailored to your circumstances, always consult a licensed attorney in your jurisdiction.
              </p>

              <h2 className="font-display text-2xl font-bold text-foreground mt-12 mb-4">2. Accuracy & Reliability</h2>
              <p className="text-muted-foreground mb-8">
                We strive for accuracy in all our AI-generated content, but we cannot guarantee that information is complete, current, or error-free. Laws and regulations change frequently, and AI systems may produce inaccurate or incomplete results. Always verify information with authoritative sources or a qualified professional before taking action.
              </p>

              <h2 className="font-display text-2xl font-bold text-foreground mt-12 mb-4">3. No Guarantees</h2>
              <p className="text-muted-foreground mb-8">
                We make no guarantees regarding outcomes, enforceability of documents, success of claims, or any other results from using our Services. Legal outcomes depend on many factors beyond the scope of our tools. Use our Services at your own risk.
              </p>

              <h2 className="font-display text-2xl font-bold text-foreground mt-12 mb-4">4. User Responsibility</h2>
              <p className="text-muted-foreground mb-8">
                You are solely responsible for any actions you take based on information or documents generated by Reluno Legal AI. This includes decisions about legal matters, filing documents, sending communications, or any other use of our outputs. We are not liable for any losses, damages, or legal consequences resulting from your use of our Services.
              </p>

              <h2 className="font-display text-2xl font-bold text-foreground mt-12 mb-4">5. Emergency Situations</h2>
              <p className="text-muted-foreground mb-8">
                Reluno Legal AI is not intended for legal emergencies. If you are facing an urgent legal matter—such as imminent arrest, emergency protective orders, or time-sensitive court deadlines—seek immediate professional legal help. Do not rely on our AI tools for emergency situations.
              </p>

              <h2 className="font-display text-2xl font-bold text-foreground mt-12 mb-4">6. Jurisdiction</h2>
              <p className="text-muted-foreground mb-8">
                Laws vary significantly by country, state, province, and local jurisdiction. Our AI tools provide general information that may not be applicable or accurate in your specific location. Always verify that any legal information or documents are appropriate for your jurisdiction.
              </p>

              <h2 className="font-display text-2xl font-bold text-foreground mt-12 mb-4">7. Third-Party Content</h2>
              <p className="text-muted-foreground mb-8">
                Our Services may contain links to third-party websites, resources, or services. We do not endorse or control these external resources and are not responsible for their content, accuracy, or practices.
              </p>

              <h2 className="font-display text-2xl font-bold text-foreground mt-12 mb-4">8. Limitation of Liability</h2>
              <p className="text-muted-foreground mb-8">
                To the fullest extent permitted by law, Reluno Legal AI and its officers, directors, employees, and affiliates shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of our Services, including but not limited to loss of profits, data, or goodwill. Our total liability for any claims shall not exceed the amount you paid for our Services in the 12 months preceding the claim.
              </p>

              <h2 className="font-display text-2xl font-bold text-foreground mt-12 mb-4">9. Indemnification</h2>
              <p className="text-muted-foreground mb-8">
                You agree to indemnify and hold harmless Reluno Legal AI from any claims, damages, or expenses arising from your use of our Services, your violation of these disclaimers, or your infringement of any third-party rights.
              </p>

              <h2 className="font-display text-2xl font-bold text-foreground mt-12 mb-4">10. Contact</h2>
              <p className="text-muted-foreground mb-8">
                For questions about these disclaimers: support@reluno.com
              </p>

              <div className="bg-muted/30 border border-border rounded-xl p-6 mt-12">
                <p className="text-sm text-muted-foreground">
                  By using Reluno Legal AI, you acknowledge that you have read, understood, and agree to these disclaimers. If you do not agree, please do not use our Services.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>
    </PageLayout>
  );
};

export default Disclaimers;
